name: Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:  
  unit:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    environment: Preview
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: Install pnpm
      run: npm i -g pnpm@8.8.0
    - name: Install dependencies
      run: pnpm i 
    - name: Build app
      run: pnpm build 
    - name: Run Unit tests
      run: pnpm test